name: Test github artifacts

on:
  push:
    branches:
      # - 'master'
      - 'cache-docker-artifacts'

jobs:
  build:
    name: Test github artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_STATE
      - name: prepare docker images tags
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMG="${REGISTRY}/${{ github.repository }}"
          IMAGE=$(echo "$IMG" | tr '[:upper:]' '[:lower:]')
          TAGS="${IMAGE}:${{ github.sha }}"
          TAGS="${TAGS},${IMAGE}:latest,${IMAGE}:v${{ steps.date.outputs.date }}"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry        
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test cargo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ci
          tags: ${{ steps.prep.outputs.tags }}
          target: test-base
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Copy artifact from from container
        uses: shrink/actions-docker-extract@v3
        with:
          image: ${{ steps.prep.outputs.tags }}
          path: /usr/src/noir/target
          destination: /dist
      - name: Copy .cargo from container
        uses: shrink/actions-docker-extract@v3
        with:
          image: ${{ steps.prep.outputs.tags }}
          path: /usr/local/cargo/
          destination: /cargo
      - name: test-dist
        run: tar -czvf /dist /dist.tar
      - name: test-cargo
        run: tar -czvf /cargo /cargo.tar
      - name: test-cache
        uses: actions/cache/save@v3
        with:
          path: |
            /dist.tar
            /cargo.tar
          key: ${{ runner.os }}-docker-artifact-cache